authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),

    re_path(r'^edit/$', authapp.edit, name='edit'),

]

basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.basket, name='view'),
    re_path(r'^add/(?P<pk>\d+)/$', basketapp.add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', basketapp.remove, name='remove'),
    re_path(r'^edit/(?P<pk>\d+)/(?P<value>\d+)/$', basketapp.edit),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import re_path, include
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),

    re_path(r'^products/', include('mainapp.urls', namespace='products')),

    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),

    re_path(r'^contact/$', mainapp.contact, name='contact'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<category_pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', \
                                  max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, \
                                decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
import json
import random
from mainapp.models import ProductCategory, Product
from basketapp.models import Basket


def get_basket(request):
    if request.user.is_authenticated:
        return Basket.objects.filter(user=request.user)


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def main(request):
    context = {
        'page_title': 'главная',
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_pk=None):
    title = 'каталог'
    categories = ProductCategory.objects.all()

    if category_pk:
        if category_pk == '0':
            category = {'name': 'все'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=category_pk)
            products = Product.objects.filter(category__pk=category_pk).order_by('price')

        content = {
            'title': title,
            'categories': categories,
            'category': category,
            'products': products,
            'basket': get_basket(request),
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'page_title': title,
        'categories': categories,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    context = {
        'product': product,
        'categories': ProductCategory.objects.all(),
        'category': product.category,
        'basket': get_basket(request),
    }

    return render(request, 'mainapp/product.html', context)


def contact(request):
    contacts = [
        {
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'phone': '+7-999-999-9999',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'phone': '+7-111-111-1111',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
    ]

    context = {
        'page_title': 'контакты',
        'contacts': contacts,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/includes/inc_links_menu.html
<ul class="links-menu">
    {#{ request.resolver_match.kwargs }#}
    <li>
        <a href="{% url 'products:category' 0 %}"
           class="{% if request.resolver_match.kwargs.category_pk == '0' %}active{% endif %}">
            все
        </a>
    </li>
    {% for category in categories %}
        <li>
            <a href="{% url 'products:category' category.pk %}"
            class="{% if request.resolver_match.kwargs.category_pk|add:0 == category.pk %}active{% endif %}">
                {{ category.name }}
            </a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
{#{ request.resolver_match.url_name }#}
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}"
           {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}"
            class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}"
            {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %}
          {{ basket.0.total_cost|floatformat:0 }} руб
          ({{ basket.0.total_quantity }} шт)
        {% endif %}
    </span>
</a>