adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main, name='main'),
    re_path(r'^user/create/$', adminapp.user_create, name='user_create'),
    re_path(r'^user/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    # re_path(r'^user/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),

    # re_path(r'^add/(?P<pk>\d+)/$', adminapp.add, name='add'),
    # re_path(r'^remove/(?P<pk>\d+)/$', adminapp.remove, name='remove'),
    # re_path(r'^edit/(?P<pk>\d+)/(?P<value>\d+)/$', adminapp.edit),

]

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),

    re_path(r'^edit/$', authapp.edit, name='edit'),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import re_path, include
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),

    re_path(r'^products/', include('mainapp.urls', namespace='products')),

    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),

    re_path(r'^contact/$', mainapp.contact, name='contact'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, \
    UserCreationForm, UserChangeForm
# import django.contrib.auth.forms as forms
from django import forms
from authapp.models import ShopUser




class ShopUserCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password', 'is_superuser')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from authapp.models import ShopUser
from django.contrib.auth.decorators import user_passes_test
from adminapp.forms import ShopUserCreateForm,ShopUserUpdateForm
from django.urls import reverse


# Create your views here.
@user_passes_test
def main(request):
    title = 'админка/пользователи'

    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    context = {
        'title': title,
        'objects': users_list
    }
    return render(request, 'adminapp/users.html', context)

def user_create(request):
    title = 'новый пользователь'

    if request.method == 'POST':
        form = ShopUserCreateForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:main'))
    else:
        form = ShopUserCreateForm()

    context = {
        'title': title,
        'form': form
    }

    return render(request, 'adminapp/user_update.html', context)


def user_update(request, pk):
    title = 'редактирование пользователя'
    updated_user = get_object_or_404(ShopUser, pk=int(pk)

    if request.method == 'POST':
        form = ShopUserUpdateForm(request.POST, request.FILES, instance=updated_user)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:main'))
    else:
        form = ShopUserUpdateForm(instance=updated_user)

    context = {
        'title': title,
        'form': form
    }

    return render(request, 'adminapp/user_update.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="admin_container">        
        <div class="h2 text-center head">
            Админка
        </div>
        {% block menu %}
            <div class="admin_menu">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}
        
        
        {% block container %}

        {% endblock %}
        
	</div>
</body>
</html>

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input class="form-control" type="submit" value="создать">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:main' %}">
                к списку пользователей
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="users_list">
		<button class="new_user">
			<a href="{% url 'admin:user_create' %}">новый пользователь</a>
		</button>
		{% for object in objects %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
					<button>
						<a href="{% url 'admin:user_update' object.pk %}">редактировать</a>
					</button>
					<button>
						<a href="{% url 'admin:user_delete' object.pk %}">удалить</a>
					</button>
				</div>
				<div class="user_name">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					<p>
					{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% if object.last_name %}
							<p>{{ object.last_name|title }}</p>
						{% endif %}
					{% endif %}
					</p>
				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}