authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),

    re_path(r'^edit/$', authapp.edit, name='edit'),

]

basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.basket, name='view'),
    re_path(r'^add/(?P<pk>\d+)/$', basketapp.add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', basketapp.remove, name='remove'),
    re_path(r'^edit/(?P<pk>\d+)/(?P<value>\d+)/$', basketapp.edit),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import re_path, include
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),

    re_path(r'^products/', include('mainapp.urls', namespace='products')),

    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),

    re_path(r'^contact/$', mainapp.contact, name='contact'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<category_pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', \
                                  max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, \
                                decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
import json
import random
from mainapp.models import ProductCategory, Product
from basketapp.models import Basket


def get_basket(request):
    if request.user.is_authenticated:
        return Basket.objects.filter(user=request.user)


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def main(request):
    context = {
        'page_title': 'главная',
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_pk=None):
    title = 'каталог'
    categories = ProductCategory.objects.all()

    if category_pk:
        if category_pk == '0':
            category = {'name': 'все'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=category_pk)
            products = Product.objects.filter(category__pk=category_pk).order_by('price')

        content = {
            'title': title,
            'categories': categories,
            'category': category,
            'products': products,
            'basket': get_basket(request),
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'page_title': title,
        'categories': categories,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    context = {
        'product': product,
        'categories': ProductCategory.objects.all(),
        'category': product.category,
        'basket': get_basket(request),
    }

    return render(request, 'mainapp/product.html', context)


def contact(request):
    contacts = [
        {
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'phone': '+7-999-999-9999',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'phone': '+7-111-111-1111',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
    ]

    context = {
        'page_title': 'контакты',
        'contacts': contacts,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
            {{ page_title|title }}
		{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
	<link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
		{% block container %}
        {% endblock %}
	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
	
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block container %}
<div class="hero">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<h1>наши контакты</h1>
</div>

<div class="location">
    {% if contacts %}
        {% for contact in contacts %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>Москва</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ contact.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ contact.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ contact.address }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>Информации пока нет</h3>
    {% endif %}
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block container %}
<div class="slider">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static '/img/arrow.png' %}" alt=""></a>
	</div>
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>

<div class="featured">
	<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		<div class="block">
			<a href="#"><img src="/static/img/product-1.jpg" alt="">
				<div class="text">
					<img src="/static/img/icon-hover.png" alt="img">
					<h4>Отличный стул</h4>
					<p>Расположитесь комфортно. </p>
				</div>
			</a>
		</div>
		<div class="block">
			<a href="#"><img src="/static/img/product-2.jpg" alt="">
				<div class="text">
					<img src="/static/img/icon-hover.png" alt="">
					<h4>Стул повышенного качества</h4>
					<p>Не оторваться. </p>
				</div>
			</a>
		</div>
	</div>
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_links_menu.html' %}
        </div>
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 1">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 2">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 3">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать 
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_links_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }} 
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }} </p>
                                <p>Цена: {{ product.price }} </p>
                                <p>На складе: {{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_links_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}